import { describe, it, expect } from "vitest";
import type { Feature } from "geojson";
import type { Country } from "../types";
import { Logic } from "../logic";
import {
  navRegionOf,
  NAV_REGIONS,
  NavRegionId,
  buildFindGraph,
  DirEdges,
  FindGraph,
} from "../find-nav";
import liteData from "./fixtures/countries.json";

// The reachability guarantee has to be proven over the REAL country set, not a
// toy graph. fixtures/countries.json is a compact snapshot of the live datasets
// (regenerated by hydrating DataLayer against the jsdelivr sources), holding
// exactly the fields find-nav needs. `hasGeometry` reconstitutes the map-askable
// set so Logic.mapPool filters as it does at runtime.
interface Lite {
  id: string;
  name: string;
  cca3: string | null;
  region: string;
  subregion: string;
  centroid: [number, number] | null;
  hasGeometry: boolean;
}

const DUMMY_FEATURE = {} as Feature;
function realCountries(): Country[] {
  return (liteData as Lite[]).map((c) => ({
    id: c.id,
    name: c.name,
    cca3: c.cca3,
    region: c.region,
    subregion: c.subregion,
    centroid: c.centroid,
    neighbours: [],
    feature: c.hasGeometry ? DUMMY_FEATURE : null,
  }));
}

const REGION_IDS = new Set<NavRegionId>(NAV_REGIONS.map((r) => r.id));
const DIRS: (keyof DirEdges)[] = ["n", "e", "s", "w"];

/** BFS along n/e/s/w edges (within `ids`) from `start`; returns reached count. */
function reachCount(start: string, ids: Set<string>, g: FindGraph): number {
  const seen = new Set([start]);
  const q = [start];
  while (q.length) {
    const v = q.shift()!;
    for (const d of DIRS) {
      const t = g[v][d];
      if (t && ids.has(t) && !seen.has(t)) {
        seen.add(t);
        q.push(t);
      }
    }
  }
  return seen.size;
}

const km = (a: [number, number], b: [number, number]): number => {
  const R = 6371,
    D = Math.PI / 180;
  let dLon = b[0] - a[0];
  while (dLon > 180) dLon -= 360;
  while (dLon <= -180) dLon += 360;
  const dLat = (b[1] - a[1]) * D;
  const h =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(a[1] * D) * Math.cos(b[1] * D) * Math.sin((dLon * D) / 2) ** 2;
  return 2 * R * Math.asin(Math.min(1, Math.sqrt(h)));
};

describe("navRegionOf — partition", () => {
  const countries = realCountries();
  const pool = Logic.mapPool(countries);
  const built = buildFindGraph(countries);

  it("assigns every map-askable country to exactly one known nav-region", () => {
    expect(pool.length).toBeGreaterThan(150); // sanity: real dataset loaded
    for (const c of pool) {
      expect(REGION_IDS.has(navRegionOf(c))).toBe(true);
    }
    // region membership partitions the pool: no gaps, no duplicates.
    const assigned = Object.values(built.regions).flat();
    expect(new Set(assigned).size).toBe(assigned.length); // no country twice
    expect(new Set(assigned)).toEqual(new Set(pool.map((c) => c.id)));
    expect(assigned.length).toBe(pool.length);
  });

  it("exposes a rough position for every region for dpad layout", () => {
    expect(NAV_REGIONS.length).toBeGreaterThanOrEqual(10);
    for (const r of NAV_REGIONS) {
      expect(r.centroid).toHaveLength(2);
      expect(Number.isFinite(r.centroid[0])).toBe(true);
      expect(Number.isFinite(r.centroid[1])).toBe(true);
    }
  });
});

describe("buildFindGraph — reachability (the guarantee)", () => {
  const countries = realCountries();
  const { graph, regions } = buildFindGraph(countries);

  it("makes every nav-region strongly connected over the real dataset", () => {
    for (const [regionId, ids] of Object.entries(regions)) {
      const set = new Set(ids);
      for (const start of ids) {
        expect(
          reachCount(start, set, graph),
          `${regionId}: ${start} cannot reach all ${ids.length} members`
        ).toBe(ids.length);
      }
    }
  });

  it("only ever links countries within the same nav-region", () => {
    const regionOf = new Map<string, string>();
    for (const [rid, ids] of Object.entries(regions))
      for (const id of ids) regionOf.set(id, rid);
    for (const [id, edges] of Object.entries(graph)) {
      for (const d of DIRS) {
        const t = edges[d];
        if (t) expect(regionOf.get(t)).toBe(regionOf.get(id));
      }
    }
  });
});

describe("buildFindGraph — directional sanity", () => {
  const countries = realCountries();
  const { graph } = buildFindGraph(countries);
  const byName = (n: string) => countries.find((c) => c.name === n)!;

  it("points France east at a near central-European neighbour, not a far one", () => {
    const fr = byName("France");
    const east = fr.centroid![0];
    const eId = graph[fr.id].e;
    expect(eId).not.toBeNull();
    const target = countries.find((c) => c.id === eId)!;
    // genuinely to the east, and near (a bordering-ish neighbour, not Ukraine/Russia)
    expect(target.centroid![0]).toBeGreaterThan(east);
    expect(km(fr.centroid!, target.centroid!)).toBeLessThan(900);
  });

  it("gives an island (Japan) non-null edges into its region", () => {
    const jp = byName("Japan");
    const edges = graph[jp.id];
    expect(DIRS.some((d) => edges[d] !== null)).toBe(true);
    // its nearest mainland to the west is the Korean peninsula
    const w = countries.find((c) => c.id === edges.w)?.name;
    expect(["North Korea", "South Korea"]).toContain(w);
  });
});

describe("buildFindGraph — tie-break", () => {
  // Base at the origin; two candidates due east, mirror-imaged N/S so they're
  // exactly equidistant. The E/W tie-break must prefer the NORTHERNMOST.
  const mk = (id: string, lng: number, lat: number): Country => ({
    id,
    name: id,
    cca3: id,
    region: "Europe",
    subregion: "Western Europe", // all land in one nav-region
    centroid: [lng, lat],
    neighbours: [],
    feature: DUMMY_FEATURE,
  });

  it("prefers the northernmost of two near-tied eastern candidates", () => {
    const base = mk("BASE", 0, 0);
    const north = mk("NORTH", 10, 2);
    const south = mk("SOUTH", 10, -2);
    const { graph } = buildFindGraph([base, north, south]);
    expect(graph["BASE"].e).toBe("NORTH");
  });

  it("prefers the westernmost of two near-tied northern candidates", () => {
    const base = mk("BASE", 0, 0);
    const west = mk("WEST", -2, 10);
    const east = mk("EAST", 2, 10);
    const { graph } = buildFindGraph([base, west, east]);
    expect(graph["BASE"].n).toBe("WEST");
  });
});
